version: "3.7"

# https://blog.denisbondar.com/post/phpstorm_docker_xdebug

services:
  link-shortener-service-debug:
    build:
      context: .
      dockerfile: Dockerfile-debug
    image: link-shortener:debug
    container_name: link-shortener-service
    restart: on-failure
    working_dir: /var/www/link_shortener
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/link_shortener
    networks:
      - link-shortener-network-debug

  nginx-service-debug:
    image: nginx:1.18.0-alpine
    container_name: nginx-service
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./config/nginx/link_shortener.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/link_shortener
    networks:
      - link-shortener-network-debug

networks:
  link-shortener-network-debug:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
