version: "3.7"

# https://blog.denisbondar.com/post/phpstorm_docker_xdebug

services:
  link-shortener-service-debug:
    build:
      context: .
      dockerfile: Dockerfile-debug
    image: link-shortener:debug
    container_name: link-shortener-service
    restart: on-failure
    working_dir: /var/www/link_shortener
    environment:
      POSTGRES_DB_HOST: postgres-service-debug
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: link_shortener
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      CURRENT_DOMAIN: "http://localhost"
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/link_shortener
    networks:
      - link-shortener-network-debug
    depends_on:
      - nginx-service-debug
      - postgres-service-debug

  nginx-service-debug:
    image: nginx:1.18.0-alpine
    container_name: nginx-service
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./config/nginx/link_shortener.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/link_shortener
    networks:
      - link-shortener-network-debug

  postgres-service-debug:
    image: postgres:12.0
    container_name: postgres-service
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: link_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-link-shortener-debug-data:/var/lib/postgresql/data
    networks:
      - link-shortener-network-debug

volumes:
  postgres-link-shortener-debug-data:

networks:
  link-shortener-network-debug:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
