create table users
(
    id       int  not null generated by default as identity,
    username text not null,
    password text not null,
    primary key (id)
);

create table login_cookies
(
    id      int  not null generated by default as identity,
    value   text not null,
    user_id int  not null references users (id) on delete cascade
);

create table links
(
    id            int  not null generated by default as identity,
    original_link text not null,
    short_link    text not null,
    user_id       int references users (id) on delete cascade,
    primary key (id)
);

create table reviews
(
    id       int  not null generated by default as identity,
    username text not null,
    message  text not null,
    primary key (id)
);
